students <- c(45, 50, 40, 55)
subjects <- c("Math","Science",  "English","Computer")
sales <- c(30, 25, 20, 25)
labels <- c("Electronics", "Clothing", "Food", "Books")
marks <- c(45,50,55,60,65,70,75,80,85,90)
height <- c(150,155,160,165,170)
weight <- c(50,55,60,65,70)
barplot(students, names.arg = subjects, col = "skyblue", main = "Bar Chart", xlab = "Subjects",  ylab = "Students")
pie(sales, labels=labels,  col= c("red","green",  "blue","yellow"), main = "Pie Chart")
hist(marks,  col = "lightgreen",  main = "Histogram",  xlab = "Marks")
plot(sales1, type = "l", col="blue",  lwd=2,  main="Line Chart",  xlab = "Month",  ylab = "Sales")
plot(height, weight,  pch = 19,  col = "red",  main = "Scatter Plot",  xlab = "Height (cm)",  ylab = "Weight (kg)")
boxplot(marks, col="orange", main="Box Plot", ylab="Marks")
plot(density(marks), col="purple", lwd = 2, main="Density Plot", xlab="Marks")
plot(sales1, type="l",  col="blue", lwd=2,  ylim=c(80, 190),  main="Multiple Line Plot")
lines(sales2, col="red", lwd=2)
legend("topleft", legend=c("Product A","Product B"), col=c("blue","red"), lty=1)
plot(sales1, type = "h", col="blue",  lwd=2,  main="Line Chart",  xlab = "Month",  ylab = "Sales")

